spring:
    datasource:
        url: jdbc:mysql://localhost:3306/dorebookstore?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: 111111
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
#        show-sql: true
        properties:
            hibernate:
                format_sql: true
    data:
        mongodb:
            uri: mongodb://localhost:27017
            database: test

server:
    port: 8181
